# Model arguments
model_name_or_path: alignment-handbook/zephyr-7b-sft-full
# https://github.com/uclaml/SPIN/issues/28
model_revision: ac6e600eefcce74f5e8bae1035d4f66019e93190
# torch_dtype: null
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 0.0005
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.01
do_eval: true
evaluation_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: zephyr-7b-kto-full-debug
hub_model_revision: kto-beta-0.01
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
# optim: adamw_torch
optim: adafactor
output_dir: data/zephyr-7b-kto-full-debug
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
loss_type: kto_pair
# report_to:
# - tensorboard